In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv('./shuju.csv',index_col=0)
data=data[data.Survived.notnull()]
data.isnull().sum()

Age             0
Embarked        0
Fare            0
Parch           0
Pclass          0
Sex             0
SibSp           0
Survived        0
professional    0
Cabin_cat       0
FamilySize      0
is_alone?       0
level           0
dtype: int64

In [3]:
data.head()

Age  Embarked     Fare  Parch  Pclass  Sex  SibSp  Survived  professional  \
0   22         0   7.2500      0       3    0      1       0.0             1   
1   38         1  71.2833      0       1    1      1       1.0             3   
2   26         0   7.9250      0       3    1      0       1.0             2   
3   35         0  53.1000      0       1    1      1       1.0             3   
4   35         0   8.0500      0       3    0      0       0.0             1   

   Cabin_cat  FamilySize  is_alone?  level  
0          0           2          0      1  
1          1           2          0      2  
2          0           1          1      1  
3          1           2          0      2  
4          0           1          1      2

In [4]:
x=data.drop('Survived',axis=1)
y=data.Survived

In [7]:
x.dtypes

Age               int64
Embarked          int64
Fare            float64
Parch             int64
Pclass            int64
Sex               int64
SibSp             int64
professional      int64
Cabin_cat         int64
FamilySize        int64
is_alone?         int64
level             int64
dtype: object

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

# 利用相关性进行特征选择

In [20]:
from scipy.stats import pearsonr
p=[]
for i in (x.columns):
    print(i)
    print(pearsonr(x[i],y))
    print('相关系数：%s'%pearsonr(x[i],y)[0])
    p.append(pearsonr(x[i],y)[0])
print(p)
print(pd.DataFrame(p,index=x.columns,columns=['相关系数值']).sort_values(by='相关系数值'))   
    
    

Age
(-0.07100930763791505, 0.03406501500378273)
相关系数：-0.07100930763791505
Embarked
(0.10681138570891947, 0.0014083124205684283)
相关系数：0.10681138570891947
Fare
(0.2573065223849624, 6.120189341917992e-15)
相关系数：0.2573065223849624
Parch
(0.08162940708348347, 0.014799245374712841)
相关系数：0.08162940708348347
Pclass
(-0.3384810359610153, 2.537047387978631e-25)
相关系数：-0.3384810359610153
Sex
(0.5433513806577551, 1.406066130878875e-69)
相关系数：0.5433513806577551
SibSp
(-0.03532249888573556, 0.2922439286980196)
相关系数：-0.03532249888573556
professional
(0.40775315641965215, 5.153081178700784e-37)
相关系数：0.40775315641965215
Cabin_cat
(0.31671324163457704, 3.2908559947377833e-22)
相关系数：0.31671324163457704
FamilySize
(0.016638989282745213, 0.6198911221336836)
相关系数：0.016638989282745213
is_alone?
(-0.2033670856998919, 9.009490179320951e-10)
相关系数：-0.2033670856998919
level
(-0.06507391623152406, 0.05216574552164164)
相关系数：-0.06507391623152406
[-0.07100930763791505, 0.10681138570891947, 0.2573065223849624, 0.081629407

In [21]:
# pearson 系数
from scipy.stats import  pearsonr
columns=X_train.columns
p=[]
for i in columns:
    print(i)
    print(pearsonr(x=X_train[i],y=y_train))
    print('pearsonr 相关性为%s'%pearsonr(X_train[i],y_train)[0])
    p.append([i,pearsonr(X_train[i],y_train)[0]])
    print('*'*50)
print('P',p)

Age
(-0.06387932000159208, 0.0885198334271036)
pearsonr 相关性为-0.06387932000159208
**************************************************
Embarked
(0.11008614924030752, 0.0032689314981643723)
pearsonr 相关性为0.11008614924030752
**************************************************
Fare
(0.26992846235149714, 2.3649706527882585e-13)
pearsonr 相关性为0.26992846235149714
**************************************************
Parch
(0.11303929947590557, 0.0025223127230549597)
pearsonr 相关性为0.11303929947590557
**************************************************
Pclass
(-0.35636581595621714, 9.568044273008842e-23)
pearsonr 相关性为-0.35636581595621714
**************************************************
Sex
(0.546254441495388, 1.2603135934089752e-56)
pearsonr 相关性为0.546254441495388
**************************************************
SibSp
(-0.020049372414112566, 0.5932739532857771)
pearsonr 相关性为-0.020049372414112566
**************************************************
professional
(0.43833470164280286, 8.642805260138102e-35

In [22]:
feature_importance=p
feature_importance.sort(key=lambda x:x[1]) #排序

In [23]:
[x[1] for x in p]

[-0.35636581595621714,
 -0.23013572975246005,
 -0.06387932000159208,
 -0.05469886247469535,
 -0.020049372414112566,
 0.04481224930069207,
 0.11008614924030752,
 0.11303929947590557,
 0.26992846235149714,
 0.34339195159049973,
 0.43833470164280286,
 0.546254441495388]

In [24]:
feature_importance

[['Pclass', -0.35636581595621714],
 ['is_alone?', -0.23013572975246005],
 ['Age', -0.06387932000159208],
 ['level', -0.05469886247469535],
 ['SibSp', -0.020049372414112566],
 ['FamilySize', 0.04481224930069207],
 ['Embarked', 0.11008614924030752],
 ['Parch', 0.11303929947590557],
 ['Fare', 0.26992846235149714],
 ['Cabin_cat', 0.34339195159049973],
 ['professional', 0.43833470164280286],
 ['Sex', 0.546254441495388]]

# 利用模型进行筛选


In [25]:
#检验
import xgboost as xgb


In [26]:
dtrain=xgb.DMatrix(X_train,label=y_train)
dtest=xgb.DMatrix(X_test,label=y_test)


In [ ]:
xgb.

In [29]:
params={
    'booster':'gbtree',
    'object':'rank:pairwise',
    'eval_metric':'auc',
    'gama':0.1,
    'min_child_weight':2,
    'max_depth':5,
    'lambda':10,
    'subsample':0.8,
    'colsample bytree':0.8,
    'eta':0.01,
    'tree_method':'exact',
    'seed':0,
    'nthead':7
}

watchlist=[(dtrain,'train_N'),(dtest,'tets_T')]

model=xgb.train(params,dtrain,num_boost_round=10,evals=watchlist)

[0]	train_N-auc:0.889227	tets_T-auc:0.817136
[1]	train_N-auc:0.891337	tets_T-auc:0.827022
[2]	train_N-auc:0.897824	tets_T-auc:0.827152
[3]	train_N-auc:0.898596	tets_T-auc:0.832256
[4]	train_N-auc:0.898789	tets_T-auc:0.830447
[5]	train_N-auc:0.90009	tets_T-auc:0.833807
[6]	train_N-auc:0.900879	tets_T-auc:0.847764
[7]	train_N-auc:0.900476	tets_T-auc:0.846278
[8]	train_N-auc:0.900253	tets_T-auc:0.845632
[9]	train_N-auc:0.900413	tets_T-auc:0.844986


In [30]:
#删除一些重要性不高的

delete_featuer=['Pclass']
X_train_delete=X_train.drop(delete_featuer,axis=1)
X_test_delete=X_test.drop(delete_featuer,axis=1)

dtrain_delete=xgb.DMatrix(X_train_delete,label=y_train)
dtest_delete=xgb.DMatrix(X_test_delete,label=y_test)

params={
    'booster':'gbtree',
    'object':'rank:pairwise',
    'eval_metric':'auc',
    'gama':0.1,
    'min_child_weight':2,
    'max_depth':5,
    'lambda':10,
    'subsample':0.8,
    'colsample bytree':0.8,
    'eta':0.01,
    'tree_method':'exact',
    'seed':0,
    'nthead':7
}

watchlist=[(dtrain_delete,'train'),(dtest_delete,'tets')]

model=xgb.train(params,dtrain_delete,num_boost_round=10,evals=watchlist)

[0]	train-auc:0.877412	tets-auc:0.813905
[1]	train-auc:0.883374	tets-auc:0.813905
[2]	train-auc:0.88775	tets-auc:0.814164
[3]	train-auc:0.890175	tets-auc:0.815133
[4]	train-auc:0.890641	tets-auc:0.815973
[5]	train-auc:0.890339	tets-auc:0.817976
[6]	train-auc:0.890725	tets-auc:0.818429
[7]	train-auc:0.891186	tets-auc:0.820109
[8]	train-auc:0.891182	tets-auc:0.819656
[9]	train-auc:0.894954	tets-auc:0.832256


# 基于模型选择

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score,ShuffleSplit

import numpy as np
from sklearn.metrics import roc_auc_score,roc_curve

In [29]:
rf=RandomForestClassifier(n_estimators=200,
                          max_depth=7,
                          min_samples_leaf=6,
                          random_state=0)
rf.fit(X_train,y_train)
pred=rf.predict(X_test)

print(roc_auc_score(pred,y_test))


0.7952904238618524


In [35]:
tpr,fpr,threshold=roc_curve(y_test,rf.predict_proba(X_test)[:,1])

In [36]:
threshold

array([1.98256227, 0.98256227, 0.91146337, 0.90086923, 0.8600068 ,
       0.84847313, 0.81203249, 0.79400339, 0.77055638, 0.68491124,
       0.66875147, 0.63309432, 0.5996673 , 0.58161001, 0.56892436,
       0.56830853, 0.48836212, 0.47556709, 0.46661319, 0.46469458,
       0.44918852, 0.4344907 , 0.4330447 , 0.42225793, 0.42110254,
       0.41957791, 0.39746925, 0.39340748, 0.3925616 , 0.38562443,
       0.37264123, 0.32893245, 0.32294881, 0.28034633, 0.27133261,
       0.18262769, 0.17609276, 0.17494184, 0.17038383, 0.16097398,
       0.15635173, 0.14173737, 0.14127903, 0.14104668, 0.13527325,
       0.11426539, 0.11218648, 0.11101261, 0.11048993, 0.10507347,
       0.10431635, 0.10424856, 0.10351325, 0.10271413, 0.09688635,
       0.0960938 , 0.08466768, 0.08423184, 0.07858348, 0.07665845,
       0.05678358, 0.0555733 , 0.04177847])

In [62]:
feature_importance=[]

for i in range(len(X_train.columns)):
    '''计算每各特征的值'''
    score=cross_val_score(rf,X=X_train.values[:,i:i+1],y=y_train,
                          scoring='r2',
                          cv=ShuffleSplit(n_splits=10,test_size=0.3,random_state=0))
    feature_importance.append([X_train.columns[i],np.mean(score)])
    feature_importance.sort(key=lambda x:x[1] )

In [66]:
feature_importance

[['Age', -0.63943835751598388],
 ['is_alone?', -0.62922951550236295],
 ['Parch', -0.60933570912290591],
 ['level', -0.53855649163859043],
 ['SibSp', -0.5346426386176274],
 ['Embarked', -0.52015453986577487],
 ['Pclass', -0.46089242634533856],
 ['FamilySize', -0.39716224952316953],
 ['Fare', -0.35661552357827014],
 ['Cabin_cat', -0.28656081743476519],
 ['Sex', 0.075206208243043721],
 ['professional', 0.11418967445481842]]

In [71]:
rf.feature_importances_

array([ 0.06080282,  0.01831161,  0.11077858,  0.01363728,  0.08758755,
        0.25242957,  0.02553964,  0.27840005,  0.05586149,  0.06502587,
        0.01116563,  0.02045991])

In [72]:
X_train.columns

Index(['Age', 'Embarked', 'Fare', 'Parch', 'Pclass', 'Sex', 'SibSp',
       'professional', 'Cabin_cat', 'FamilySize', 'is_alone?', 'level'],
      dtype='object')

# 利用xgboost进行特征选择

In [81]:
params={
    'booster':'gbtree',
    'object':'rank:pairwise',
    'eval_metric':'auc',
    'gama':0.1,
    'min_child_weight':2,
    'max_depth':5,
    'lambda':10,
    'subsample':0.8,
    'colsample bytree':0.8,
    'eta':0.01,
    'tree_method':'exact',
    'seed':0,
    'nthead':7
}

watchlist=[(dtrain,'train'),(dtest,'tets')]

model=xgb.train(params,dtrain,num_boost_round=10,evals=watchlist)

[0]	train-auc:0.879508	tets-auc:0.797807
[1]	train-auc:0.882202	tets-auc:0.811831
[2]	train-auc:0.884519	tets-auc:0.805966
[3]	train-auc:0.886264	tets-auc:0.810811
[4]	train-auc:0.88943	tets-auc:0.81795
[5]	train-auc:0.893975	tets-auc:0.830189
[6]	train-auc:0.894282	tets-auc:0.833248
[7]	train-auc:0.894123	tets-auc:0.832228
[8]	train-auc:0.894827	tets-auc:0.833248
[9]	train-auc:0.894794	tets-auc:0.834778


In [87]:
score=model.get_score();score #利用xgboost进行特征选择

{'Age': 37,
 'Cabin_cat': 14,
 'Embarked': 6,
 'FamilySize': 10,
 'Fare': 41,
 'Parch': 9,
 'Pclass': 19,
 'Sex': 3,
 'SibSp': 6,
 'professional': 19}

In [88]:
sorted(score,key=lambda x:x[1])

['Cabin_cat',
 'Fare',
 'FamilySize',
 'Parch',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Embarked',
 'professional']

# 利用正则化---L1

In [89]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)

In [90]:
from sklearn.linear_model import LogisticRegression

In [92]:
lr=LogisticRegression(penalty='l1',random_state=0,n_jobs=-1).fit(X_train,y_train)
pred=lr.predict(X_test)
print(roc_auc_score(pred,y_test))

0.784138655462


In [94]:
lr.coef_ #权重，如果权重越低，越不重要

array([[-0.02744548,  0.20151151,  0.00264257, -0.19608371, -0.56985284,
         2.1991179 , -0.41724485,  0.5397144 ,  0.61779283, -0.15719754,
        -0.5639447 , -0.15606968]])

In [98]:
lr.coef_[0]

array([-0.02744548,  0.20151151,  0.00264257, -0.19608371, -0.56985284,
        2.1991179 , -0.41724485,  0.5397144 ,  0.61779283, -0.15719754,
       -0.5639447 , -0.15606968])

In [95]:
feature_importance=[(i[0],i[1])for i in zip(X_train.columns,lr.coef_[0])]

In [104]:
import numpy as np
feature_importance.sort(key=lambda x: np.abs(x[1]))

In [105]:
feature_importance

[('Fare', 0.0026425685656718931),
 ('Age', -0.027445482409325348),
 ('level', -0.1560696848255054),
 ('FamilySize', -0.15719753886798798),
 ('Parch', -0.19608371418826717),
 ('Embarked', 0.20151150660383529),
 ('SibSp', -0.41724485060361105),
 ('professional', 0.53971440086858258),
 ('is_alone?', -0.56394470017813703),
 ('Pclass', -0.56985283770491002),
 ('Cabin_cat', 0.61779282761801901),
 ('Sex', 2.1991179048394796)]

# 利用L2进行 

In [106]:
lr=LogisticRegression(penalty='l2',random_state=0,n_jobs=-1).fit(X_train,y_train)
pred=lr.predict(X_test)
print(roc_auc_score(pred,y_test))

0.784138655462


In [107]:
feature_importance=[(i[0],i[1])for i in zip(X_train.columns,lr.coef_[0])]
feature_importance.sort(key=lambda x: np.abs(x[1]))
feature_importance

[('Fare', 0.0026425685656718931),
 ('Age', -0.027445482409325348),
 ('level', -0.1560696848255054),
 ('FamilySize', -0.15719753886798798),
 ('Parch', -0.19608371418826717),
 ('Embarked', 0.20151150660383529),
 ('SibSp', -0.41724485060361105),
 ('professional', 0.53971440086858258),
 ('is_alone?', -0.56394470017813703),
 ('Pclass', -0.56985283770491002),
 ('Cabin_cat', 0.61779282761801901),
 ('Sex', 2.1991179048394796)]

# 基于稳定性

In [108]:
from sklearn.linear_model import RandomizedLasso #Randomized Lasso.
rlassso=RandomizedLasso(alpha=0.025)

In [113]:
from sklearn.datasets import load_boston
X,y=load_boston().data,load_boston().target
rlassso.fit(X,y)

RandomizedLasso(alpha=0.025, eps=2.2204460492503131e-16, fit_intercept=True,
        max_iter=500, memory=Memory(cachedir=None), n_jobs=1,
        n_resampling=200, normalize=True, pre_dispatch='3*n_jobs',
        precompute='auto', random_state=None, sample_fraction=0.75,
        scaling=0.5, selection_threshold=0.25, verbose=False)

In [118]:
feature=[(i[0],i[1]) for i in zip(load_boston().feature_names,rlassso.scores_)]

In [120]:
feature.sort(key=lambda x:x[1]);feature

[('AGE', 0.0050000000000000001),
 ('RAD', 0.014999999999999999),
 ('ZN', 0.050000000000000003),
 ('INDUS', 0.095000000000000001),
 ('DIS', 0.17999999999999999),
 ('NOX', 0.23000000000000001),
 ('TAX', 0.39500000000000002),
 ('CRIM', 0.435),
 ('CHAS', 0.65000000000000002),
 ('B', 0.66500000000000004),
 ('RM', 1.0),
 ('PTRATIO', 1.0),
 ('LSTAT', 1.0)]

# 基于递归算法 （每次删除一个）

In [121]:
from sklearn.feature_selection import  RFE

In [123]:
x=data.drop('Survived',axis=1)
y=data.Survived
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)

In [124]:
rf=RandomForestClassifier()
rfe=RFE(rf,n_features_to_select=1,verbose=1)#每次选择一个特征
rfe.fit(X_train,y_train)

Fitting estimator with 12 features.
Fitting estimator with 11 features.
Fitting estimator with 10 features.
Fitting estimator with 9 features.
Fitting estimator with 8 features.
Fitting estimator with 7 features.
Fitting estimator with 6 features.
Fitting estimator with 5 features.
Fitting estimator with 4 features.
Fitting estimator with 3 features.
Fitting estimator with 2 features.


RFE(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False),
  n_features_to_select=1, step=1, verbose=1)

In [126]:
feature_importance=rfe.ranking_;feature_importance

array([ 3, 10,  1, 11,  5,  4,  9,  2,  7,  6, 12,  8])

In [127]:
feature_importance=sorted(zip(map(lambda x:round(x,4),rfe.ranking_),X_train.columns))

In [128]:
feature_importance

[(1, 'Fare'),
 (2, 'professional'),
 (3, 'Age'),
 (4, 'Sex'),
 (5, 'Pclass'),
 (6, 'FamilySize'),
 (7, 'Cabin_cat'),
 (8, 'level'),
 (9, 'SibSp'),
 (10, 'Embarked'),
 (11, 'Parch'),
 (12, 'is_alone?')]